# Config file for Goemon's Great Adventure (USA) Recompilation.

[input]
entrypoint = 0x80000400
output_func_path = "/home/bazzite/recomp/Goemon64Recomp/RecompiledFuncs"
rom_file_path = "/home/bazzite/recomp/gga.us.decompressed.z64"
symbols_file_path = "gga.splat.syms.toml"
trace_mode = true
bss_section_suffix = "_bss"

[patches]
stubs = ["func_80024478", "func_80024470", "func_800204E0", "func_8001E860", "func_8001C050", "func_8001AD00", "func_8001AC80", "func_8001A9A0", "func_80014A50", "func_80013D80", "func_80012150", "func_800104D4", "func_8000FC90", "func_8000FD50"]
