# Config file for Goemon's Great Adventure (USA) Recompilation.

[input]
entrypoint = 0x80000400
output_func_path = "/home/bazzite/recomp/Goemon64Recomp/RecompiledFuncs"
rom_file_path = "/home/bazzite/recomp/gga.us.z64"
symbols_file_path = "/home/bazzite/recomp/gga.syms.toml"
trace_mode = true
bss_section_suffix = "_bss"

[patches]
stubs = ["FUN_8002138c", "FUN_80020a70", "FUN_8001e860", "FUN_8001cd30", "FUN_8001c450", "FUN_8001c050", "FUN_80016070", "FUN_80014ef0", "FUN_80014a50", "FUN_80014774", "FUN_80014390", "FUN_80013360", "FUN_80012150", "FUN_8000df54", "FUN_8000b2ac", "FUN_8000a098", "FUN_80008028", "FUN_80005f50", "FUN_80001a24", "func_8001AC80", "__osProbeTLB" ]
ignored = []






[[patches.instruction]]
func = "FUN_80012150"
vram = 0x80012188
value = 0x00000000

[[patches.instruction]]
func = "FUN_80012150"
vram = 0x800121AC
value = 0x00000000







[[patches.instruction]]
func = "FUN_800204e0"
vram = 0x800204F0
value = 0x00000000

[[patches.instruction]]
func = "FUN_8001ac78"
vram = 0x8001ACB8
value = 0x00000000

[[patches.instruction]]
func = "FUN_8001accc"
vram = 0x8001ACDC
value = 0x00000000

[[patches.instruction]]
func = "FUN_8001ad00"
vram = 0x8001AD3C
value = 0x00000000

[[patches.instruction]]
func = "FUN_8001ad00"
vram = 0x8001AD60
value = 0x00000000

[[patches.instruction]]
func = "FUN_8001ad00"
vram = 0x8001AD70
value = 0x00000000

[[patches.instruction]]
func = "FUN_8001ad84"
vram = 0x8001AD94
value = 0x00000000
