#!/usr/bin/env python3
"""Convert Ghidra XML export to N64Recomp syms.toml format."""
import xml.etree.ElementTree as ET
import sys

xml_path = "/home/bazzite/recomp/gga_export.xml"
out_path = "/home/bazzite/recomp/gga.syms.toml"

print(f"Parsing {xml_path}...")
tree = ET.parse(xml_path)
root = tree.getroot()

# Collect functions by memory block
blocks = {}
for block in root.iter("MEMORY_SECTION"):
    name = block.get("NAME")
    start = int(block.get("START_ADDR", "0x0"), 16)
    length = int(block.get("LENGTH", "0x0"), 16)
    perms = block.get("PERMISSIONS", "")
    if "x" not in perms:
        continue
    blocks[name] = {
        "start": start,
        "end": start + length,
        "size": length,
        "rom": int(block.get("FILE_OFFSET", "0x0"), 16),
        "functions": []
    }

# Assign functions to blocks
for func in root.iter("FUNCTION"):
    entry = func.get("ENTRY_POINT")
    name = func.get("NAME")
    if not entry or not name:
        continue
    fvram = int(entry, 16)
    # Find body size
    fsize = 4  # default
    address_range = func.find("ADDRESS_RANGE")
    if address_range is not None:
        start = int(address_range.get("START", entry), 16)
        end = int(address_range.get("END", entry), 16)
        fsize = max(4, end - start + 1)

    for bname, binfo in blocks.items():
        if binfo["start"] <= fvram < binfo["end"]:
            binfo["functions"].append((fvram, name, fsize))
            break

# Write syms.toml
with open(out_path, "w") as f:
    f.write("# Autogenerated from Ghidra XML export\n\n")
    for bname, binfo in blocks.items():
        f.write("[[section]]\n")
        f.write(f'name = "{bname}"\n')
        f.write(f"rom = 0x{binfo['rom']:08X}\n")
        f.write(f"vram = 0x{binfo['start']:08X}\n")
        f.write(f"size = 0x{binfo['size']:X}\n")
        f.write("functions = [\n")
        for fvram, fname, fsize in sorted(binfo["functions"]):
            f.write(f'    {{ name = "{fname}", vram = 0x{fvram:08X}, size = 0x{fsize:X} }},\n')
        f.write("]\n\n")

print(f"Wrote {out_path}")
func_count = sum(len(b["functions"]) for b in blocks.values())
print(f"Sections: {len(blocks)}, Functions: {func_count}")
