#!/usr/bin/env python3
"""splat_to_syms.py -- convert splat's disassembly (.s files) into a complete
N64Recomp symbols TOML.

splat emits `glabel func_<VRAM>` per discovered function, and every instruction
line carries `/* <rom_off> <vram> <word> */`. A function's VRAM is taken from its
first instruction line; its size is (next function's VRAM - this VRAM), with the
last function sized by its final instruction line + 4. The ROM offset of the first
function and its VRAM give the section's rom<->vram mapping.

Usage:
    splat_to_syms.py ASM_DIR --section .main --out gga.syms.toml [--entry-vram 0x80000400]

The result mirrors N64Recomp's expected layout:
    [[section]]
    name = ".main"
    rom  = 0x...        # rom offset of the section's first function
    vram = 0x...        # vram of the section's first function
    size = 0x...        # spans first function start .. last function end
    functions = [ { name = "func_8000...", vram = 0x..., size = 0x... }, ... ]
"""
import argparse, glob, os, re, sys

# `/* <rom_hex> <vram_hex> <word_hex> */  <mnemonic> ...`
INSTR_RE  = re.compile(r'/\*\s*([0-9A-Fa-f]+)\s+([0-9A-Fa-f]{8})\s+[0-9A-Fa-f]{8}\s*\*/')
GLABEL_RE = re.compile(r'^\s*glabel\s+(\w+)\s*$')

def parse_functions(asm_dir):
    """A function spans from its `glabel` to the NEXT `glabel` (or end of file). Within
    that span, its last real instruction line fixes the end. Internal labels (.L...:),
    blank lines, %hi/%lo macros, and stray directives do NOT end the function -- only the
    next glabel does. Start VRAM comes from the glabel name (func_8000XXXX) when present,
    else from the first instruction line."""
    funcs = {}                          # start_vram -> [rom_off, name, last_instr_vram]
    for path in sorted(glob.glob(os.path.join(asm_dir, "**", "*.s"), recursive=True)):
        cur = None                      # start_vram key of the function being accumulated
        pending = None                  # glabel name awaiting its first instruction
        for line in open(path, errors="replace"):
            g = GLABEL_RE.match(line)
            if g:
                pending = g.group(1); cur = None; continue   # next glabel ends prior func
            m = INSTR_RE.search(line)
            if not m:
                continue                # internal label / blank / macro -> keep accumulating
            rom_off = int(m.group(1), 16); vram = int(m.group(2), 16)
            if pending is not None:                          # first instruction of a function
                nm = re.match(r'(?:func|entrypoint|main)_?([0-9A-Fa-f]{8})$', pending)
                start = int(nm.group(1), 16) if nm else vram
                funcs.setdefault(start, [rom_off - (vram - start), pending, vram])
                cur = start; pending = None
            if cur is not None and vram > funcs[cur][2]:     # extend to this instruction
                funcs[cur][2] = vram
    if not funcs:
        sys.exit(f"no glabel functions found under {asm_dir} (is this splat asm output?)")
    return sorted((v, rom, nm, last) for v, (rom, nm, last) in funcs.items())

def build_sizes(ordered):
    """size = (last instruction vram + 4) - start, clamped to never cross the next function."""
    out = []
    for i, (vram, rom, name, last) in enumerate(ordered):
        size = last + 4 - vram
        if i + 1 < len(ordered):
            size = min(size, ordered[i + 1][0] - vram)
        if size <= 0:
            sys.exit(f"non-positive size for {name} @ {vram:#x} -> {size:#x}")
        out.append((vram, rom, name, size))
    return out

def emit_toml(sized, section_name, rom_path, syms_rel):
    first_vram, first_rom, _, _ = sized[0]
    last_vram, _, _, last_size = sized[-1]
    section_size = (last_vram + last_size) - first_vram
    L = []
    L.append("# Generated by splat_to_syms.py from splat disassembly.")
    L.append(f"# {len(sized)} functions; section spans "
             f"{first_vram:#010x}..{last_vram + last_size:#010x}\n")
    L.append("[[section]]")
    L.append(f'name = "{section_name}"')
    L.append(f"rom = {first_rom:#x}")
    L.append(f"vram = {first_vram:#x}")
    L.append(f"size = {section_size:#x}")
    L.append("functions = [")
    for vram, rom, name, size in sized:
        L.append(f'  {{ name = "{name}", vram = {vram:#x}, size = {size:#x} }},')
    L.append("]")
    return "\n".join(L) + "\n"

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("asm_dir")
    ap.add_argument("--section", default=".main")
    ap.add_argument("--out", default="gga.syms.toml")
    ap.add_argument("--rom", default="gga.us.z64")
    args = ap.parse_args()

    ordered = parse_functions(args.asm_dir)
    sized = build_sizes(ordered)
    toml_text = emit_toml(sized, args.section, args.rom, args.out)
    with open(args.out, "w") as f:
        f.write(toml_text)
    print(f"wrote {args.out}: {len(sized)} functions, "
          f"section {sized[0][0]:#x}..{sized[-1][0] + sized[-1][3]:#x} "
          f"(rom base {sized[0][1]:#x})")
    print(f"  first: {sized[0][2]} @ {sized[0][0]:#x} size {sized[0][3]:#x}")
    print(f"  last:  {sized[-1][2]} @ {sized[-1][0]:#x} size {sized[-1][3]:#x}")

if __name__ == "__main__":
    main()
