[[section]]
name = ".entry"
rom = 0x00001000
vram = 0x80000400
size = 0x50
functions = [
    { name = "recomp_entrypoint", vram = 0x80000400, size = 0x38 },
]

[[section]]
name = ".main"
rom = 0x00001050
vram = 0x80000450
size = 0x7EC00
functions = [
    { name = "FUN_800006dc", vram = 0x800006DC, size = 0x8 },
]
