# Exports function symbols in N64Recomp syms.toml format
# @category N64

import os

out_path = "/home/bazzite/recomp/gga.syms.toml"
mem = currentProgram.getMemory()
fm = currentProgram.getFunctionManager()

with open(out_path, "w") as f:
    f.write("# Autogenerated by ExportN64RecompSyms.py from Ghidra analysis\n\n")

    for block in mem.getBlocks():
        if not block.isExecute():
            continue

        block_start = block.getStart().getOffset()
        block_end = block.getEnd().getOffset()
        rom_offset = block.getFileOffset()
        size = block.getSize()

        f.write("[[section]]\n")
        f.write('name = "{}"\n'.format(block.getName()))
        f.write("rom = 0x{:08X}\n".format(rom_offset))
        f.write("vram = 0x{:08X}\n".format(block_start))
        f.write("size = 0x{:X}\n".format(size))
        f.write("functions = [\n")

        for func in fm.getFunctions(block.getStart(), True):
            fvram = func.getEntryPoint().getOffset()
            if fvram > block_end:
                break
            fsize = func.getBody().getNumAddresses()
            f.write('    {{ name = "{}", vram = 0x{:08X}, size = 0x{:X} }},\n'.format(
                func.getName(), fvram, fsize))

        f.write("]\n\n")

print("Wrote syms to: " + out_path)
