// Exports function symbols in N64Recomp syms.toml format
// Run via: Ghidra Script Manager → ExportN64RecompSyms.java
//@category N64

import ghidra.app.script.GhidraScript;
import ghidra.program.model.listing.*;
import ghidra.program.model.mem.*;
import java.io.*;

public class ExportN64RecompSyms extends GhidraScript {
    public void run() throws Exception {
        String outPath = System.getProperty("user.home") + "/recomp/gga.syms.toml";
        PrintWriter out = new PrintWriter(new FileWriter(outPath));
        out.println("# Autogenerated by ExportN64RecompSyms.java from Ghidra analysis");
        out.println();

        Memory mem = currentProgram.getMemory();
        FunctionManager fm = currentProgram.getFunctionManager();

        for (MemoryBlock block : mem.getBlocks()) {
            if (!block.isExecute()) continue;

            long blockStart = block.getStart().getOffset();
            long blockEnd   = block.getEnd().getOffset();
            long romOffset  = block.getFileOffset();
            long size       = block.getSize();

            out.println("[[section]]");
            out.printf("name = \"%s\"%n", block.getName());
            out.printf("rom = 0x%08X%n", romOffset);
            out.printf("vram = 0x%08X%n", blockStart);
            out.printf("size = 0x%X%n", size);
            out.println("functions = [");

            for (Function f : fm.getFunctions(block.getStart(), true)) {
                long fVram = f.getEntryPoint().getOffset();
                if (fVram > blockEnd) break;
                long fSize = f.getBody().getNumAddresses();
                out.printf("    { name = \"%s\", vram = 0x%08X, size = 0x%X },%n",
                    f.getName(), fVram, fSize);
            }

            out.println("]");
            out.println();
        }

        out.close();
        println("Wrote syms to: " + outPath);
    }
}
